### ISSUE TITLE
Make constants for all required css properties 

### ISSUE THREAD

**Issue by hofmanndavid** [vernesoftware/responsive-layout#4]
When building layouts we should not make the users use hard coded strings.

**Comment by Jayrok94** [comment]
@hofmanndavid I believe this is already the case

Example?

**Comment by hofmanndavid** [comment]
responsiveLayout.addStyleName("content-center");

**Comment by Jayrok94** [comment]
Ahhh.. that was in the demo..

It is actually now a method as of version 1.0.1
Column.centerContent(true);

Hasn't been removed from the demo though thank you.

**Comment by hofmanndavid** [comment]
I believe the default should be centered. And that centerContent call be made to undo the default

**Comment by Jayrok94** [comment]
I believe the default for things such as vertical layout and horizontal layout is left. I think we should reflect the default behaviors of responsive layout the same.
